version: "3"

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=friendly_notes
      - POSTGRES_USER=friendly_notes
      - POSTGRES_PASSWORD=password
  web:
    build: .
    command: >
      bash -c "python manage.py migrate 
      && python manage.py runserver 0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
